{
 "title": "Desktop",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "gpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "power_draw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "NVIDIA GeForce RTX 3060" }
     ]
    },
    {
     "alias": "package",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat",
     "select": [
      [
       { "params": [ "package_power_watt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "core::tag", "operator": "=", "value": "-" },
      { "condition": "AND", "key": "cpu::tag", "operator": "=", "value": "-" }
     ]
    },
    {
     "alias": "core",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat",
     "select": [
      [
       { "params": [ "core_power_watt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "core::tag", "operator": "=", "value": "-" },
      { "condition": "AND", "key": "cpu::tag", "operator": "=", "value": "-" }
     ]
    },
    {
     "alias": "package-rapl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rapl",
     "query": "SELECT mean(\"power\") FROM (SELECT non_negative_derivative(mean(\"energy_joules\"), 1s) AS \"power\" FROM \"rapl\" WHERE (\"host\"::tag = 'desktop' AND \"power_zone\"::tag = 'intel-rapl:0') AND $timeFilter GROUP BY time(10s) fill(null)) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "energy_joules" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "power_zone::tag", "operator": "=", "value": "intel-rapl:0" }
     ]
    },
    {
     "alias": "core-rapl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rapl",
     "query": "SELECT mean(\"power\") FROM (SELECT non_negative_derivative(mean(\"energy_joules\"), 1s) AS \"power\" FROM \"rapl\" WHERE (\"host\"::tag = 'desktop' AND \"power_zone\"::tag = 'intel-rapl:0:0') AND $timeFilter GROUP BY time(10s) fill(null)) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "energy_joules" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "* 8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "power_zone::tag", "operator": "=", "value": "intel-rapl:0:0" }
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "tsi0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "nct6799_tsi0_temp" }
     ]
    },
    {
     "alias": "systin",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "nct6799_systin" }
     ]
    },
    {
     "alias": "amd_gpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "amdgpu_edge" }
     ]
    },
    {
     "alias": "nvidia_gpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "temperature_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "NVIDIA GeForce RTX 3060" }
     ]
    },
    {
     "alias": "ssd0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "WDS500G3X0C-00SJG0" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "203252808911" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature_Celsius" }
     ]
    },
    {
     "alias": "ssd1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "S466NB0K412967V" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature_Celsius" }
     ]
    },
    {
     "alias": "ssd_sata",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "model", "operator": "=", "value": "CT2000MX500SSD1" },
      { "condition": "AND", "key": "serial_no", "operator": "=", "value": "2052E4E205F2" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Temperature_Celsius" }
     ]
    },
    {
     "alias": "wifi",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "mt7921_phy0" }
     ]
    }
   ]
  },
  {
   "title": "Fans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feature::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "feature::tag", "operator": "=", "value": "fan2" }
     ]
    },
    {
     "alias": "cha1_bottom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feature::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "feature::tag", "operator": "=", "value": "fan4" }
     ]
    },
    {
     "alias": "cha2_back",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feature::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "feature::tag", "operator": "=", "value": "fan5" }
     ]
    },
    {
     "alias": "cha3_top",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feature::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "fan_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "feature::tag", "operator": "=", "value": "fan7" }
     ]
    }
   ]
  },
  {
   "title": "Cores frequencies",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "cpu_[[tag_cpu]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat",
     "select": [
      [
       { "params": [ "average_frequency_mhz" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "cpu::tag", "operator": "!=", "value": "-" },
      { "condition": "AND", "key": "core::tag", "operator": "!=", "value": "-" }
     ]
    },
    {
     "alias": "cpu_average",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat",
     "select": [
      [
       { "params": [ "average_frequency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "cpu::tag", "operator": "=", "value": "-" },
      { "condition": "AND", "key": "core::tag", "operator": "=", "value": "-" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "idle",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "guest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "guest_nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_guest_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "iowait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "irq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "softirq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "steal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    }
   ]
  },
  {
   "title": "C-States",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "c1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat",
     "select": [
      [
       { "params": [ "c1_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "core::tag", "operator": "=", "value": "-" },
      { "condition": "AND", "key": "cpu::tag", "operator": "=", "value": "-" }
     ]
    },
    {
     "alias": "c2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat",
     "select": [
      [
       { "params": [ "c2_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "core::tag", "operator": "=", "value": "-" },
      { "condition": "AND", "key": "cpu::tag", "operator": "=", "value": "-" }
     ]
    },
    {
     "alias": "c3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "turbostat",
     "select": [
      [
       { "params": [ "c3_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "core::tag", "operator": "=", "value": "-" },
      { "condition": "AND", "key": "cpu::tag", "operator": "=", "value": "-" }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "load15",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "load5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "load1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    }
   ]
  },
  {
   "title": "CPU memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" }
     ]
    }
   ]
  },
  {
   "title": "GPU memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "NVIDIA GeForce RTX 3060" }
     ]
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidia_smi",
     "select": [
      [
       { "params": [ "memory_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "NVIDIA GeForce RTX 3060" }
     ]
    }
   ]
  },
  {
   "title": "Wi-Fi I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "recv",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface::tag", "operator": "=", "value": "wlp5s0" }
     ]
    },
    {
     "alias": "sent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface::tag", "operator": "=", "value": "wlp5s0" }
     ]
    }
   ]
  },
  {
   "title": "Wi-Fi link quality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "link quality",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wireless",
     "query": "SELECT mean(\"link\") FROM \"wireless\" WHERE (\"host\" = 'desktop' AND \"interface\" = 'wlo1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlp5s0" }
     ]
    },
    {
     "alias": "link quality_avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wireless",
     "query": "SELECT mean(\"link\") FROM \"wireless\" WHERE (\"host\" = 'desktop' AND \"interface\" = 'wlo1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "link" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "12" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlo1" }
     ]
    }
   ]
  },
  {
   "title": "SSD1 I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "ID_MODEL", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "ID_SERIAL_SHORT", "operator": "=", "value": "S466NB0K412967V" }
     ]
    },
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "ID_MODEL", "operator": "=", "value": "Samsung SSD 970 EVO 500GB" },
      { "condition": "AND", "key": "ID_SERIAL_SHORT", "operator": "=", "value": "S466NB0K412967V" }
     ]
    }
   ]
  },
  {
   "title": "SSD (SATA) I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "ID_MODEL", "operator": "=", "value": "CT2000MX500SSD1" },
      { "condition": "AND", "key": "ID_SERIAL_SHORT", "operator": "=", "value": "2052E4E205F2" }
     ]
    },
    {
     "alias": "write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "desktop" },
      { "condition": "AND", "key": "ID_MODEL", "operator": "=", "value": "CT2000MX500SSD1" },
      { "condition": "AND", "key": "ID_SERIAL_SHORT", "operator": "=", "value": "2052E4E205F2" }
     ]
    }
   ]
  }
 ]
}